/********************************************************************************
** Form generated from reading UI file 'scheduleview.ui'
**
** Created by: Qt User Interface Compiler version 6.9.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SCHEDULEVIEW_H
#define UI_SCHEDULEVIEW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ScheduleView
{
public:
    QFrame *frame_5;
    QLabel *label_3;
    QLabel *dateRangeLabel;
    QLabel *docLabel;
    QFrame *frame;
    QFrame *frame_11;
    QFrame *frame20;
    QFrame *frame21;
    QFrame *frame22;
    QFrame *frame23;
    QFrame *frame24;
    QFrame *frame25;
    QFrame *frame26;
    QFrame *frame27;
    QFrame *frame_8;
    QFrame *frame10;
    QFrame *frame11;
    QFrame *frame12;
    QFrame *frame13;
    QFrame *frame14;
    QFrame *frame15;
    QFrame *frame16;
    QFrame *frame17;
    QFrame *frame_7;
    QFrame *frame00;
    QFrame *frame01;
    QFrame *frame02;
    QFrame *frame03;
    QFrame *frame04;
    QFrame *frame05;
    QFrame *frame06;
    QFrame *frame07;
    QFrame *frame_10;
    QFrame *frame30;
    QFrame *frame31;
    QFrame *frame32;
    QFrame *frame33;
    QFrame *frame34;
    QFrame *frame35;
    QFrame *frame36;
    QFrame *frame37;
    QFrame *frame_9;
    QFrame *frame40;
    QFrame *frame41;
    QFrame *frame42;
    QFrame *frame43;
    QFrame *frame44;
    QFrame *frame45;
    QFrame *frame46;
    QFrame *frame47;
    QFrame *frame_3;
    QLabel *label_2;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QFrame *frame_49;
    QLabel *label_4;
    QLabel *label_8;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QFrame *frame_50;
    QPushButton *arrowLeft;
    QFrame *frame_98;
    QPushButton *arrowRight;

    void setupUi(QWidget *ScheduleView)
    {
        if (ScheduleView->objectName().isEmpty())
            ScheduleView->setObjectName("ScheduleView");
        ScheduleView->resize(1471, 901);
        frame_5 = new QFrame(ScheduleView);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(0, 0, 1471, 901));
        frame_5->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);\n"
"border-radius: 10px;"));
        frame_5->setFrameShape(QFrame::Shape::StyledPanel);
        frame_5->setFrameShadow(QFrame::Shadow::Raised);
        label_3 = new QLabel(frame_5);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(120, 10, 1231, 61));
        QFont font;
        font.setPointSize(18);
        font.setBold(true);
        label_3->setFont(font);
        label_3->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        label_3->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_3->setTextFormat(Qt::TextFormat::RichText);
        label_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        dateRangeLabel = new QLabel(frame_5);
        dateRangeLabel->setObjectName("dateRangeLabel");
        dateRangeLabel->setGeometry(QRect(120, 130, 1231, 20));
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        dateRangeLabel->setFont(font1);
        dateRangeLabel->setAlignment(Qt::AlignmentFlag::AlignCenter);
        docLabel = new QLabel(frame_5);
        docLabel->setObjectName("docLabel");
        docLabel->setGeometry(QRect(120, 80, 1231, 41));
        QFont font2;
        font2.setPointSize(14);
        font2.setBold(true);
        docLabel->setFont(font2);
        docLabel->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        docLabel->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        docLabel->setTextFormat(Qt::TextFormat::RichText);
        docLabel->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame = new QFrame(frame_5);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(20, 170, 1431, 701));
        frame->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        frame->setFrameShape(QFrame::Shape::StyledPanel);
        frame->setFrameShadow(QFrame::Shadow::Raised);
        frame_11 = new QFrame(frame);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(640, 110, 251, 571));
        frame_11->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 41, 94);"));
        frame_11->setFrameShape(QFrame::Shape::StyledPanel);
        frame_11->setFrameShadow(QFrame::Shadow::Raised);
        frame20 = new QFrame(frame_11);
        frame20->setObjectName("frame20");
        frame20->setGeometry(QRect(10, 10, 231, 61));
        frame20->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame20->setFrameShape(QFrame::Shape::StyledPanel);
        frame20->setFrameShadow(QFrame::Shadow::Raised);
        frame21 = new QFrame(frame_11);
        frame21->setObjectName("frame21");
        frame21->setGeometry(QRect(10, 80, 231, 61));
        frame21->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame21->setFrameShape(QFrame::Shape::StyledPanel);
        frame21->setFrameShadow(QFrame::Shadow::Raised);
        frame22 = new QFrame(frame_11);
        frame22->setObjectName("frame22");
        frame22->setGeometry(QRect(10, 150, 231, 61));
        frame22->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame22->setFrameShape(QFrame::Shape::StyledPanel);
        frame22->setFrameShadow(QFrame::Shadow::Raised);
        frame23 = new QFrame(frame_11);
        frame23->setObjectName("frame23");
        frame23->setGeometry(QRect(10, 220, 231, 61));
        frame23->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame23->setFrameShape(QFrame::Shape::StyledPanel);
        frame23->setFrameShadow(QFrame::Shadow::Raised);
        frame24 = new QFrame(frame_11);
        frame24->setObjectName("frame24");
        frame24->setGeometry(QRect(10, 290, 231, 61));
        frame24->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame24->setFrameShape(QFrame::Shape::StyledPanel);
        frame24->setFrameShadow(QFrame::Shadow::Raised);
        frame25 = new QFrame(frame_11);
        frame25->setObjectName("frame25");
        frame25->setGeometry(QRect(10, 360, 231, 61));
        frame25->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame25->setFrameShape(QFrame::Shape::StyledPanel);
        frame25->setFrameShadow(QFrame::Shadow::Raised);
        frame26 = new QFrame(frame_11);
        frame26->setObjectName("frame26");
        frame26->setGeometry(QRect(10, 430, 231, 61));
        frame26->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame26->setFrameShape(QFrame::Shape::StyledPanel);
        frame26->setFrameShadow(QFrame::Shadow::Raised);
        frame27 = new QFrame(frame_11);
        frame27->setObjectName("frame27");
        frame27->setGeometry(QRect(10, 500, 231, 61));
        frame27->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame27->setFrameShape(QFrame::Shape::StyledPanel);
        frame27->setFrameShadow(QFrame::Shadow::Raised);
        frame_8 = new QFrame(frame);
        frame_8->setObjectName("frame_8");
        frame_8->setGeometry(QRect(380, 110, 251, 571));
        frame_8->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 41, 94);"));
        frame_8->setFrameShape(QFrame::Shape::StyledPanel);
        frame_8->setFrameShadow(QFrame::Shadow::Raised);
        frame10 = new QFrame(frame_8);
        frame10->setObjectName("frame10");
        frame10->setGeometry(QRect(10, 10, 231, 61));
        frame10->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame10->setFrameShape(QFrame::Shape::StyledPanel);
        frame10->setFrameShadow(QFrame::Shadow::Raised);
        frame11 = new QFrame(frame_8);
        frame11->setObjectName("frame11");
        frame11->setGeometry(QRect(10, 80, 231, 61));
        frame11->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame11->setFrameShape(QFrame::Shape::StyledPanel);
        frame11->setFrameShadow(QFrame::Shadow::Raised);
        frame12 = new QFrame(frame_8);
        frame12->setObjectName("frame12");
        frame12->setGeometry(QRect(10, 150, 231, 61));
        frame12->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame12->setFrameShape(QFrame::Shape::StyledPanel);
        frame12->setFrameShadow(QFrame::Shadow::Raised);
        frame13 = new QFrame(frame_8);
        frame13->setObjectName("frame13");
        frame13->setGeometry(QRect(10, 220, 231, 61));
        frame13->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame13->setFrameShape(QFrame::Shape::StyledPanel);
        frame13->setFrameShadow(QFrame::Shadow::Raised);
        frame14 = new QFrame(frame_8);
        frame14->setObjectName("frame14");
        frame14->setGeometry(QRect(10, 290, 231, 61));
        frame14->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame14->setFrameShape(QFrame::Shape::StyledPanel);
        frame14->setFrameShadow(QFrame::Shadow::Raised);
        frame15 = new QFrame(frame_8);
        frame15->setObjectName("frame15");
        frame15->setGeometry(QRect(10, 360, 231, 61));
        frame15->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame15->setFrameShape(QFrame::Shape::StyledPanel);
        frame15->setFrameShadow(QFrame::Shadow::Raised);
        frame16 = new QFrame(frame_8);
        frame16->setObjectName("frame16");
        frame16->setGeometry(QRect(10, 430, 231, 61));
        frame16->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame16->setFrameShape(QFrame::Shape::StyledPanel);
        frame16->setFrameShadow(QFrame::Shadow::Raised);
        frame17 = new QFrame(frame_8);
        frame17->setObjectName("frame17");
        frame17->setGeometry(QRect(10, 500, 231, 61));
        frame17->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame17->setFrameShape(QFrame::Shape::StyledPanel);
        frame17->setFrameShadow(QFrame::Shadow::Raised);
        frame_7 = new QFrame(frame);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(120, 110, 251, 571));
        frame_7->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 41, 94);"));
        frame_7->setFrameShape(QFrame::Shape::StyledPanel);
        frame_7->setFrameShadow(QFrame::Shadow::Raised);
        frame00 = new QFrame(frame_7);
        frame00->setObjectName("frame00");
        frame00->setGeometry(QRect(10, 10, 231, 61));
        frame00->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame00->setFrameShape(QFrame::Shape::StyledPanel);
        frame00->setFrameShadow(QFrame::Shadow::Raised);
        frame01 = new QFrame(frame_7);
        frame01->setObjectName("frame01");
        frame01->setGeometry(QRect(10, 80, 231, 61));
        frame01->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame01->setFrameShape(QFrame::Shape::StyledPanel);
        frame01->setFrameShadow(QFrame::Shadow::Raised);
        frame02 = new QFrame(frame_7);
        frame02->setObjectName("frame02");
        frame02->setGeometry(QRect(10, 150, 231, 61));
        frame02->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame02->setFrameShape(QFrame::Shape::StyledPanel);
        frame02->setFrameShadow(QFrame::Shadow::Raised);
        frame03 = new QFrame(frame_7);
        frame03->setObjectName("frame03");
        frame03->setGeometry(QRect(10, 220, 231, 61));
        frame03->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame03->setFrameShape(QFrame::Shape::StyledPanel);
        frame03->setFrameShadow(QFrame::Shadow::Raised);
        frame04 = new QFrame(frame_7);
        frame04->setObjectName("frame04");
        frame04->setGeometry(QRect(10, 290, 231, 61));
        frame04->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame04->setFrameShape(QFrame::Shape::StyledPanel);
        frame04->setFrameShadow(QFrame::Shadow::Raised);
        frame05 = new QFrame(frame_7);
        frame05->setObjectName("frame05");
        frame05->setGeometry(QRect(10, 360, 231, 61));
        frame05->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame05->setFrameShape(QFrame::Shape::StyledPanel);
        frame05->setFrameShadow(QFrame::Shadow::Raised);
        frame06 = new QFrame(frame_7);
        frame06->setObjectName("frame06");
        frame06->setGeometry(QRect(10, 430, 231, 61));
        frame06->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame06->setFrameShape(QFrame::Shape::StyledPanel);
        frame06->setFrameShadow(QFrame::Shadow::Raised);
        frame07 = new QFrame(frame_7);
        frame07->setObjectName("frame07");
        frame07->setGeometry(QRect(10, 500, 231, 61));
        frame07->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame07->setFrameShape(QFrame::Shape::StyledPanel);
        frame07->setFrameShadow(QFrame::Shadow::Raised);
        frame_10 = new QFrame(frame);
        frame_10->setObjectName("frame_10");
        frame_10->setGeometry(QRect(900, 110, 251, 571));
        frame_10->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 41, 94);"));
        frame_10->setFrameShape(QFrame::Shape::StyledPanel);
        frame_10->setFrameShadow(QFrame::Shadow::Raised);
        frame30 = new QFrame(frame_10);
        frame30->setObjectName("frame30");
        frame30->setGeometry(QRect(10, 10, 231, 61));
        frame30->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame30->setFrameShape(QFrame::Shape::StyledPanel);
        frame30->setFrameShadow(QFrame::Shadow::Raised);
        frame31 = new QFrame(frame_10);
        frame31->setObjectName("frame31");
        frame31->setGeometry(QRect(10, 80, 231, 61));
        frame31->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame31->setFrameShape(QFrame::Shape::StyledPanel);
        frame31->setFrameShadow(QFrame::Shadow::Raised);
        frame32 = new QFrame(frame_10);
        frame32->setObjectName("frame32");
        frame32->setGeometry(QRect(10, 150, 231, 61));
        frame32->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame32->setFrameShape(QFrame::Shape::StyledPanel);
        frame32->setFrameShadow(QFrame::Shadow::Raised);
        frame33 = new QFrame(frame_10);
        frame33->setObjectName("frame33");
        frame33->setGeometry(QRect(10, 220, 231, 61));
        frame33->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame33->setFrameShape(QFrame::Shape::StyledPanel);
        frame33->setFrameShadow(QFrame::Shadow::Raised);
        frame34 = new QFrame(frame_10);
        frame34->setObjectName("frame34");
        frame34->setGeometry(QRect(10, 290, 231, 61));
        frame34->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame34->setFrameShape(QFrame::Shape::StyledPanel);
        frame34->setFrameShadow(QFrame::Shadow::Raised);
        frame35 = new QFrame(frame_10);
        frame35->setObjectName("frame35");
        frame35->setGeometry(QRect(10, 360, 231, 61));
        frame35->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame35->setFrameShape(QFrame::Shape::StyledPanel);
        frame35->setFrameShadow(QFrame::Shadow::Raised);
        frame36 = new QFrame(frame_10);
        frame36->setObjectName("frame36");
        frame36->setGeometry(QRect(10, 430, 231, 61));
        frame36->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame36->setFrameShape(QFrame::Shape::StyledPanel);
        frame36->setFrameShadow(QFrame::Shadow::Raised);
        frame37 = new QFrame(frame_10);
        frame37->setObjectName("frame37");
        frame37->setGeometry(QRect(10, 500, 231, 61));
        frame37->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame37->setFrameShape(QFrame::Shape::StyledPanel);
        frame37->setFrameShadow(QFrame::Shadow::Raised);
        frame_9 = new QFrame(frame);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(1160, 110, 251, 571));
        frame_9->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 41, 94);"));
        frame_9->setFrameShape(QFrame::Shape::StyledPanel);
        frame_9->setFrameShadow(QFrame::Shadow::Raised);
        frame40 = new QFrame(frame_9);
        frame40->setObjectName("frame40");
        frame40->setGeometry(QRect(10, 10, 231, 61));
        frame40->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame40->setFrameShape(QFrame::Shape::StyledPanel);
        frame40->setFrameShadow(QFrame::Shadow::Raised);
        frame41 = new QFrame(frame_9);
        frame41->setObjectName("frame41");
        frame41->setGeometry(QRect(10, 80, 231, 61));
        frame41->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame41->setFrameShape(QFrame::Shape::StyledPanel);
        frame41->setFrameShadow(QFrame::Shadow::Raised);
        frame42 = new QFrame(frame_9);
        frame42->setObjectName("frame42");
        frame42->setGeometry(QRect(10, 150, 231, 61));
        frame42->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame42->setFrameShape(QFrame::Shape::StyledPanel);
        frame42->setFrameShadow(QFrame::Shadow::Raised);
        frame43 = new QFrame(frame_9);
        frame43->setObjectName("frame43");
        frame43->setGeometry(QRect(10, 220, 231, 61));
        frame43->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame43->setFrameShape(QFrame::Shape::StyledPanel);
        frame43->setFrameShadow(QFrame::Shadow::Raised);
        frame44 = new QFrame(frame_9);
        frame44->setObjectName("frame44");
        frame44->setGeometry(QRect(10, 290, 231, 61));
        frame44->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame44->setFrameShape(QFrame::Shape::StyledPanel);
        frame44->setFrameShadow(QFrame::Shadow::Raised);
        frame45 = new QFrame(frame_9);
        frame45->setObjectName("frame45");
        frame45->setGeometry(QRect(10, 360, 231, 61));
        frame45->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame45->setFrameShape(QFrame::Shape::StyledPanel);
        frame45->setFrameShadow(QFrame::Shadow::Raised);
        frame46 = new QFrame(frame_9);
        frame46->setObjectName("frame46");
        frame46->setGeometry(QRect(10, 430, 231, 61));
        frame46->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame46->setFrameShape(QFrame::Shape::StyledPanel);
        frame46->setFrameShadow(QFrame::Shadow::Raised);
        frame47 = new QFrame(frame_9);
        frame47->setObjectName("frame47");
        frame47->setGeometry(QRect(10, 500, 231, 61));
        frame47->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 149, 168);"));
        frame47->setFrameShape(QFrame::Shape::StyledPanel);
        frame47->setFrameShadow(QFrame::Shadow::Raised);
        frame_3 = new QFrame(frame);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(10, 110, 101, 571));
        frame_3->setStyleSheet(QString::fromUtf8("background-color: rgb(101, 137, 255);\n"
"color: white;"));
        frame_3->setFrameShape(QFrame::Shape::StyledPanel);
        frame_3->setFrameShadow(QFrame::Shadow::Raised);
        label_2 = new QLabel(frame_3);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 10, 81, 61));
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(true);
        label_2->setFont(font3);
        label_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_6 = new QLabel(frame_3);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 80, 81, 61));
        label_6->setFont(font3);
        label_6->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_7 = new QLabel(frame_3);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(10, 150, 81, 61));
        label_7->setFont(font3);
        label_7->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_7->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_9 = new QLabel(frame_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(10, 220, 81, 61));
        label_9->setFont(font3);
        label_9->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_9->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_10 = new QLabel(frame_3);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(10, 290, 81, 61));
        label_10->setFont(font3);
        label_10->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_10->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_14 = new QLabel(frame_3);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(10, 360, 81, 61));
        label_14->setFont(font3);
        label_14->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_14->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_15 = new QLabel(frame_3);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(10, 430, 81, 61));
        label_15->setFont(font3);
        label_15->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_15->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_16 = new QLabel(frame_3);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(10, 500, 81, 61));
        label_16->setFont(font3);
        label_16->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        label_16->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_49 = new QFrame(frame);
        frame_49->setObjectName("frame_49");
        frame_49->setGeometry(QRect(120, 20, 1291, 80));
        frame_49->setStyleSheet(QString::fromUtf8("background-color: rgb(101, 137, 255)"));
        frame_49->setFrameShape(QFrame::Shape::StyledPanel);
        frame_49->setFrameShadow(QFrame::Shadow::Raised);
        label_4 = new QLabel(frame_49);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 10, 231, 61));
        label_4->setFont(font2);
        label_4->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        label_4->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);\n"
"color: white;\n"
""));
        label_4->setTextFormat(Qt::TextFormat::RichText);
        label_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_8 = new QLabel(frame_49);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(270, 10, 231, 61));
        label_8->setFont(font2);
        label_8->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        label_8->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);\n"
"color: white;"));
        label_8->setTextFormat(Qt::TextFormat::RichText);
        label_8->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_11 = new QLabel(frame_49);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(530, 10, 231, 61));
        label_11->setFont(font2);
        label_11->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        label_11->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);\n"
"color: white;"));
        label_11->setTextFormat(Qt::TextFormat::RichText);
        label_11->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_12 = new QLabel(frame_49);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(790, 10, 231, 61));
        label_12->setFont(font2);
        label_12->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        label_12->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);\n"
"color: white;\n"
""));
        label_12->setTextFormat(Qt::TextFormat::RichText);
        label_12->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_13 = new QLabel(frame_49);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(1050, 10, 231, 61));
        label_13->setFont(font2);
        label_13->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        label_13->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);\n"
"color: white;"));
        label_13->setTextFormat(Qt::TextFormat::RichText);
        label_13->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_50 = new QFrame(frame_5);
        frame_50->setObjectName("frame_50");
        frame_50->setGeometry(QRect(20, 70, 91, 91));
        frame_50->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        frame_50->setFrameShape(QFrame::Shape::StyledPanel);
        frame_50->setFrameShadow(QFrame::Shadow::Raised);
        arrowLeft = new QPushButton(frame_50);
        arrowLeft->setObjectName("arrowLeft");
        arrowLeft->setGeometry(QRect(10, 0, 71, 81));
        QFont font4;
        font4.setPointSize(52);
        arrowLeft->setFont(font4);
        frame_98 = new QFrame(frame_5);
        frame_98->setObjectName("frame_98");
        frame_98->setGeometry(QRect(1360, 60, 91, 91));
        frame_98->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 62, 154);"));
        frame_98->setFrameShape(QFrame::Shape::StyledPanel);
        frame_98->setFrameShadow(QFrame::Shadow::Raised);
        arrowRight = new QPushButton(frame_98);
        arrowRight->setObjectName("arrowRight");
        arrowRight->setGeometry(QRect(10, 0, 71, 81));
        arrowRight->setFont(font4);

        retranslateUi(ScheduleView);

        QMetaObject::connectSlotsByName(ScheduleView);
    } // setupUi

    void retranslateUi(QWidget *ScheduleView)
    {
        ScheduleView->setWindowTitle(QCoreApplication::translate("ScheduleView", "Form", nullptr));
        label_3->setText(QCoreApplication::translate("ScheduleView", "Harmonogram", nullptr));
        dateRangeLabel->setText(QCoreApplication::translate("ScheduleView", "21.07.2025 - 27.07.2025", nullptr));
        docLabel->setText(QCoreApplication::translate("ScheduleView", "Lekarz", nullptr));
        label_2->setText(QCoreApplication::translate("ScheduleView", "8:00-9:00", nullptr));
        label_6->setText(QCoreApplication::translate("ScheduleView", "9:00-10:00", nullptr));
        label_7->setText(QCoreApplication::translate("ScheduleView", "10:00-11:00", nullptr));
        label_9->setText(QCoreApplication::translate("ScheduleView", "11:00-12:00", nullptr));
        label_10->setText(QCoreApplication::translate("ScheduleView", "12:00-13:00", nullptr));
        label_14->setText(QCoreApplication::translate("ScheduleView", "13:00-14:00", nullptr));
        label_15->setText(QCoreApplication::translate("ScheduleView", "14:00-15:00", nullptr));
        label_16->setText(QCoreApplication::translate("ScheduleView", "15:00-16:00", nullptr));
        label_4->setText(QCoreApplication::translate("ScheduleView", "Poniedzia\305\202ek", nullptr));
        label_8->setText(QCoreApplication::translate("ScheduleView", "Wtorek", nullptr));
        label_11->setText(QCoreApplication::translate("ScheduleView", "\305\232roda", nullptr));
        label_12->setText(QCoreApplication::translate("ScheduleView", "Czwartek", nullptr));
        label_13->setText(QCoreApplication::translate("ScheduleView", "Pi\304\205tek", nullptr));
        arrowLeft->setText(QCoreApplication::translate("ScheduleView", "\342\254\205\357\270\217", nullptr));
        arrowRight->setText(QCoreApplication::translate("ScheduleView", "\342\236\241\357\270\217", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ScheduleView: public Ui_ScheduleView {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SCHEDULEVIEW_H
